'use strict';

// console.log(document.querySelector('.message').textContent);

/*
//                              DOM MANIPULATION

Do JavaScript interacts with a webpage! Connexion between JS AND HTML   

- DOM (Document Object Model): Structured representation of html documents. Allows
JavaScript to access hmtl elements and stles to manipulate them. (Change text, html 
attributes and even CSS styles);

- Tree structure, generated by browser on HTML load;

- Document: special object that is the entry point to the DOM. 
Example: document.querySelector();

DOM !== JAVASCRIPT

*/


// // This is already DOM manipulation
// document.querySelector('.message').textContent = 'Correct Number 💚'
// document.querySelector('.number').textContent = 13;
// document.querySelector('.score').textContent = 10;


// // With the input field, we use value instead to use the text content
// document.querySelector('.guess').value
// document.querySelector('.guess').value = 23;


//                      Handling Click Events



// Function is just a value, so we can pass a function like an argument in another funtion
// In the addEventListener method, the first argument will be the event(action) and the second event will be an function that is going to say what is going to happen when this event happened. (event handler)
// The function only be called when the event happens


'use strict';

/*
console.log(document.querySelector('.message').textContent);
document.querySelector('.message').textContent = '🎉 Correct Number!';

document.querySelector('.number').textContent = 13;
document.querySelector('.score').textContent = 10;

document.querySelector('.guess').value = 23;
console.log(document.querySelector('.guess').value);
*/
const generateRandomNumber = function() {
    Math.trunc(Math.random() * 20) + 1;
}

let secretNumber = generateRandomNumber()
let score = 20;
let highscore = 0;

const displayMessage = function (message) {
  document.querySelector('.message').textContent = message;
};

document.querySelector('.check').addEventListener('click', function () {
  const guess = Number(document.querySelector('.guess').value);
  console.log(guess, typeof guess);

  // When there is no input
  if (!guess) {
    // document.querySelector('.message').textContent = '⛔️ No number!';
    displayMessage('⛔️ No number!');

    // When player wins
  } else if (guess === secretNumber) {
    // document.querySelector('.message').textContent = '🎉 Correct Number!';
    displayMessage('🎉 Correct Number!');
    document.querySelector('.number').textContent = secretNumber;

    document.querySelector('body').style.backgroundColor = '#60b347';
    document.querySelector('.number').style.width = '30rem';

    if (score > highscore) {
      highscore = score;
      document.querySelector('.highscore').textContent = highscore;
    }

    // When guess is wrong
  } else if (guess !== secretNumber) {
    if (score > 1) {
      // document.querySelector('.message').textContent =
      // guess > secretNumber ? '📈 Too high!' : '📉 Too low!';
      displayMessage(guess > secretNumber ? '📈 Too high!' : '📉 Too low!');
      score--;
      document.querySelector('.score').textContent = score;
    } else {
      // document.querySelector('.message').textContent = '💥 You lost the game!';
      displayMessage('💥 You lost the game!');
      document.querySelector('.score').textContent = 0;
    }
  }

  //   // When guess is too high
  // } else if (guess > secretNumber) {
  //   if (score > 1) {
  //     document.querySelector('.message').textContent = '📈 Too high!';
  //     score--;
  //     document.querySelector('.score').textContent = score;
  //   } else {
  //     document.querySelector('.message').textContent = '💥 You lost the game!';
  //     document.querySelector('.score').textContent = 0;
  //   }

  //   // When guess is too low
  // } else if (guess < secretNumber) {
  //   if (score > 1) {
  //     document.querySelector('.message').textContent = '📉 Too low!';
  //     score--;
  //     document.querySelector('.score').textContent = score;
  //   } else {
  //     document.querySelector('.message').textContent = '💥 You lost the game!';
  //     document.querySelector('.score').textContent = 0;
  //   }
  // }
});

document.querySelector('.again').addEventListener('click', function () {
  score = 20;
  secretNumber = generateRandomNumber()

  // document.querySelector('.message').textContent = 'Start guessing...';
  displayMessage('Start guessing...');
  document.querySelector('.score').textContent = score;
  document.querySelector('.number').textContent = '?';
  document.querySelector('.guess').value = '';

  document.querySelector('body').style.backgroundColor = '#222';
  document.querySelector('.number').style.width = '15rem';

});

//Refactoring the code: Don't repeat youlself. More cleaner code